# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Canteli
  params:
    description: Anderson Marcos Dias Canteli'

pt:
  languageCode: pt-br
  contentDir: content/pt
  title: Canteli
  params:
    description: Anderson Marcos Dias Canteli'
